### ISSUE TITLE
No implicit conversion from Symblo to Integer error

### ISSUE THREAD

**Issue by huesitos** [huesitos/aplus#34]
This bug appears while executing the tests. I started a stackoverflow thread about it here: http://stackoverflow.com/questions/31059008/getting-rspec-error-no-implicit-conversion-of-symbol-into-integer-with-mongoid.

**Comment by gotjosh** [comment]
I'll also take this one, so feel free to assign it to me.

**Comment by gotjosh** [comment]
Hey again! After setting up the test configuration for controllers, I came across this issue again so I decided to give it a go. 

This comes up whenever I try to query the database on test and/or development. It seemed really weird so I started digging up, after switching around the driver version a bit (Downgrade and Upgrade) I realized it's a bug for the specific version of mongoid that we're using. 

This is why I don't think it's a good idea to use the `master` version directly from the repository of any gem unless you have some pretty specific reasons. We should either upgrade to `5.0.0.beta` or downgrade to `4.0` stable, is there any specific functionality that you might need from `5.0`? Because my initial thought would be to downgrade and eventually upgrade when `5.0` becomes stable.
